// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDhAzrZNqJGQYdO783ZraS2YCqsHt1pyE',
    appId: '1:699235246168:web:1149b6e3a65d5f72e92a2d',
    messagingSenderId: '699235246168',
    projectId: 'geoquest-f35a6',
    authDomain: 'geoquest-f35a6.firebaseapp.com',
    storageBucket: 'geoquest-f35a6.firebasestorage.app',
    measurementId: 'G-Z3THNMT5LC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmqvNXoRCzOl3IS4wxSk0sWaa-sFb380M',
    appId: '1:699235246168:android:013da01ace95e8a0e92a2d',
    messagingSenderId: '699235246168',
    projectId: 'geoquest-f35a6',
    storageBucket: 'geoquest-f35a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtzXtQMlt5flSimbwmGnZpjvhdksnz1us',
    appId: '1:699235246168:ios:8ca90bd25fe091e3e92a2d',
    messagingSenderId: '699235246168',
    projectId: 'geoquest-f35a6',
    storageBucket: 'geoquest-f35a6.firebasestorage.app',
    iosClientId: '699235246168-33bk934gchlgrh3dvhgjffbc1475blui.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtzXtQMlt5flSimbwmGnZpjvhdksnz1us',
    appId: '1:699235246168:ios:8ca90bd25fe091e3e92a2d',
    messagingSenderId: '699235246168',
    projectId: 'geoquest-f35a6',
    storageBucket: 'geoquest-f35a6.firebasestorage.app',
    iosClientId: '699235246168-33bk934gchlgrh3dvhgjffbc1475blui.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDhAzrZNqJGQYdO783ZraS2YCqsHt1pyE',
    appId: '1:699235246168:web:e2c6fb11c8ffdb11e92a2d',
    messagingSenderId: '699235246168',
    projectId: 'geoquest-f35a6',
    authDomain: 'geoquest-f35a6.firebaseapp.com',
    storageBucket: 'geoquest-f35a6.firebasestorage.app',
    measurementId: 'G-SBY3Z3EQT8',
  );
}
